# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    core.twig_extension:
        class: Blog\CoreBundle\Twig\CoreExtension
        arguments:
          - "@service_container"
        tags:
          - { name: twig.extension }